# Generated by Django 3.0.6 on 2020-06-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='classificacao',
            field=models.CharField(choices=[('1', 'Telecomunicações'), ('2', 'Água'), ('3', 'Energia'), ('4', 'Alimentação'), ('5', 'Outros')], default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='forma_pagamento',
            field=models.CharField(choices=[('1', 'Boleto'), ('2', 'Crédito'), ('3', 'Débito'), ('4', 'Depósito'), ('5', 'Outros')], default=1, max_length=4),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='situacao',
            field=models.CharField(choices=[('1', 'Pago'), ('2', 'A pagar')], default=1, max_length=4),
        ),
    ]
