# Generated by Django 3.0.6 on 2020-06-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_auto_20200608_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('data_expectativa', models.DateField(null=True)),
                ('data_recebimento', models.DateField(null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('classificacao', models.CharField(choices=[('1', 'Serviços Prestados'), ('2', 'Salario'), ('3', 'Vendas'), ('4', 'Outros')], default=1, max_length=4)),
                ('forma_recebimento', models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cheque'), ('3', 'Cartão Credito'), ('4', 'Cartão Debito'), ('5', 'Deposito'), ('6', 'Vale'), ('7', 'Outros')], default=1, max_length=4)),
                ('situacao', models.CharField(choices=[('1', 'Recebido'), ('2', 'A receber')], default=1, max_length=4)),
            ],
        ),
    ]
