# Generated by Django 3.0.6 on 2020-06-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_contasreceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaspagar',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
